CREATE TABLE painting.Paints
(
    id bigint(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Number varchar(16),
    Color varchar(64),
    Triad varchar(64),
    brand_id int(11),
    family_id int(11),
    box_id int(11)
);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (1, '09003', 'Blood Red', 'Blood Colors', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (2, '09004', 'Fire Red', 'Fire Colors', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (3, '09005', 'Phoenix Red', 'Fire', 1, 35, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (4, '09006', 'Fire Orange', 'Fire Colors', 1, 35, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (5, '09007', 'Marigold Yellow', 'Yellows', 1, 35, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (6, '09008', 'Sun Yellow', 'Yellows', 1, 13, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (7, '09012', 'Pale Green', 'Warm Greens', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (8, '09013', 'Forest Green', 'Cool Greens', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (9, '09014', 'Grass Green', 'Cool Greens', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (10, '09015', 'Jade Green', 'Cool Greens', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (11, '09016', 'Sapphire Blue', 'Pure Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (12, '09017', 'True Blue', 'Pure Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (13, '09018', 'Sky Blue', 'Pure Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (14, '09020', 'Twilight Blue', 'Grey Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (15, '09021', 'Snow Shadow', 'Grey Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (16, '09022', 'Nightshade Purple', 'Royal Purples', 1, 6, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (17, '09023', 'Imperial Purple', 'Royal Purples', 1, 6, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (18, '09024', 'Amethyst Purple', 'Royal Purples', 1, 6, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (19, '09025', 'Burgundy Wine', 'Violet Reds', 1, 6, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (20, '09028', 'Muddy Brown', 'Warm Deep Browns', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (21, '09029', 'Earth Brown', 'Warm Deep Browns', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (22, '09030', 'Leather Brown', 'Warm Deep Browns', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (23, '09031', 'Tanned Leather', 'Warm Light Browns', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (24, '09032', 'Amber Gold', 'Warm Light Browns', 1, 13, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (25, '09034', 'Muddy Olive', 'Olive Greens', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (26, '09035', 'Olive Green', 'Olive Greens', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (27, '09036', 'Pale Olive', 'Olive Greens', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (28, '09037', 'Pure Black', 'Neutral Colors', 1, 21, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (29, '09038', 'Rainy Grey', 'Neutral Colors', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (30, '09039', 'Pure White', 'Neutral Colors', 1, 14, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (31, '09040', 'Dark Shadow', 'Dark Skin', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (32, '09041', 'Dark Skin', 'Dark Skin', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (33, '09042', 'Dark Highlights', 'Dark Skin', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (34, '09043', 'Tanned Shadow', 'Medium  Skin Tones', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (35, '09044', 'Tanned Skin', 'Medium  Skin Tones', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (36, '09045', 'Tanned Highlight', 'Medium  Skin Tones', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (37, '09046', 'Fair Shadow', 'Fair Skin Tones', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (38, '09047', 'Fair Skin', 'Fair Skin Tones', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (39, '09048', 'Fair Highlight', 'Fair Skin Tones', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (40, '09049', 'Ancient Bronze', 'Gold-Toned Metals', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (41, '09050', 'Antique Gold', 'Gold-Toned Metals', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (42, '09051', 'New Gold', 'Gold-Toned Metals', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (43, '09053', 'Honed Steel', 'Silver-Toned Metals', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (44, '09054', 'Polished Silver', 'Silver-toned Metals', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (45, '09055', 'Breonne Blue', 'Martial Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (46, '09056', 'Templar Blue', 'Martial Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (47, '09057', 'Ashen Blue', 'Martial Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (48, '09058', 'Bone Shadow', 'Bone Colors', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (49, '09061', 'Linen White', 'Off-Whites', 1, 14, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (50, '09062', 'Leather White', 'Off-Whites', 1, 14, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (51, '09063', 'Ghost White', 'Off-Whites', 1, 14, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (52, '09064', 'Brown Liner', 'Liners', 1, 19, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (53, '09065', 'Grey Liner', 'Liners', 1, 19, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (54, '09066', 'Blue Liner', 'Liners', 1, 19, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (55, '09068', 'Rosy Skin', 'Rosy Skin', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (56, '09071', 'Chestnut Brown', 'Red-Brown', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (57, '09083', 'Highland Moss', 'Moss Colors', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (58, '09084', 'Pale Lichen', 'Moss Colors', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (59, '09085', 'Shadowed Stone', 'Stone Colors', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (60, '09086', 'Stone Grey', 'Stone Colors', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (61, '09087', 'Weathered Stone', 'Stone Colors', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (62, '09089', 'Vloudy Grey', 'Neutral Greys', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (63, '09090', 'Misty Grey', 'Neutral Greys', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (64, '09091', 'Golden Shadow', 'Golden Skintones', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (65, '09092', 'Golden Skin', 'Golden Skintones', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (66, '09093', 'Golden Highlight', 'Golden Skin', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (67, '09095', 'Clear Yellow', '', 1, 13, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (68, '09098', 'Clear Magenta', 'Clear Brights Two', 1, 6, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (69, '09100', 'Pearl White', 'Colored Metallics One', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (70, '09101', 'Ruby Red', 'Colored Metallics One', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (71, '09102', 'Coppery Orange', 'Colored Metallics One', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (72, '09103', 'Emerald Green', 'Colored Metallics Two', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (73, '09104', 'Sparkling Blue', 'Colored Metallics One', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (74, '09105', 'Sparkling Amethyst', 'Colored Metallics Two', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (75, '09106', 'Flow Improver', 'Additives', 1, 12, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (76, '09107', 'Brush-on Sealer', 'Additives', 1, 12, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (77, '09108', 'Brush-on Primer', 'Additives', 1, 12, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (78, '09109', 'Ruddy Leather', 'Burnt Colors', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (79, '09110', 'Oiled Leather', 'Burnt Colors', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (80, '09111', 'Burnt Orange', 'Burnt Colors', 1, 35, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (81, '09116', 'Brilliant Blue', 'Vivid Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (82, '09121', 'Khaki Shadow', 'Terran Khakis', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (83, '09122', 'Terran Khaki', 'Terran Khakis', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (84, '09124', 'Adamantium Black', 'Colored Metallics Three', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (85, '09125', 'Scorched Metal', 'Colored Metallics Three', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (86, '09126', 'Gunmetal Blue', 'Colored Metallics Three', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (87, '09127', 'Uniform Brown', 'Khaki Browns', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (88, '09129', 'Faded Khaki', 'Khaki Browns', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (89, '09133', 'Bloodstain Red', 'Bloodthirsty Reds', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (90, '09134', 'Clotted Red', 'Bloodthirsty Reds', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (91, '09135', 'Carnage Red', 'Bloodthirsty Reds', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (92, '09136', 'Walnut Brown', 'Classic Browns', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (93, '09137', 'Blackened Brown', 'Classic Browns', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (94, '09142', 'Stained Ivory', 'Ivory Bone Colors', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (95, '09143', 'Yellowed Bone', 'Ivory Bone Triad', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (96, '09144', 'Creamy Ivory', 'Ivory Bone Triad', 1, 14, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (97, '09148', 'Ghoul Skin', 'Undead Skin Tones', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (98, '09149', 'Moldy Skin', 'Undead Skin Tones', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (99, '09150', 'Bloodless Skin', 'Undead Skin Tones', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (100, '09157', 'Olive Shadow', 'Olive Drabs', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (101, '09158', 'Olive Drab', 'Olive Drabs', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (102, '09159', 'Worn Olive', 'Olive Drabs', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (103, '09162', 'Driftwood Brown', 'Cool Browns', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (104, '09163', 'Dark Elf Shadow', 'Dark Elf Skin', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (105, '09164', 'Dark Elf Skin', 'Dark Elf Skin', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (106, '09165', 'Dark Elf Highlight', 'Dark Elf Skin', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (107, '09198', 'Tarnished Brass', 'Metallic Colors V', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (108, '09200', 'Harvest Brown', 'Autumn Browns', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (109, '09205', 'Blackened Steel', 'Natural Steel', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (110, '09206', 'Tarnished Steel', 'Natural Steel', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (111, '09207', 'True Silver', 'Natural Steel', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (112, '09214', 'Black Primer', 'Additives II', 1, 12, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (113, '09218', 'Lava Orange', 'Lava Colors', 1, 35, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (114, '09219', 'Explosion Orange', 'Lava Colors', 1, 35, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (115, '09223', 'Redstone Shadow', 'Redstone Triad', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (116, '09225', 'Redstone Highlight', '', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (117, '09226', 'Peacock Green', 'Brilliant Greens', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (118, '09227', 'Brilliant Green', 'Brilliant Greens', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (119, '09228', 'Viper Green', 'Brilliant Greens', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (120, '09229', 'Worn Navy', 'Weathered Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (121, '09230', 'Soft Blue', 'Weathered Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (122, '09231', 'Heather Blue', 'Weathered Blues', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (123, '09234', 'Bright Skin Highlight', 'Bright Skintones', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (124, '09235', 'Red Shadow', 'Shading Colors', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (125, '09236', 'Black Green', 'Shadng Colors', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (126, '09237', 'Violet Shadow', 'Shading Colors', 1, 6, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (127, '09241', 'Auburn Shadow', 'Red Hair', 1, 18, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (128, '09242', 'Carrot Top Red', 'Red Hair', 1, 18, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (129, '09243', 'Highlight Orange', 'Red Hair', 1, 18, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (130, '09244', 'Muddy Soil', 'Soil Colors', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (131, '09246', 'Brown Sand', 'Soil Colors', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (132, '09247', 'Saffron Sunset', 'Old Favorites I', 1, 35, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (133, '09248', 'Moth Green', 'Old Favorites I', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (134, '09250', 'Dusky Skin Shadow', 'Dusky Skin', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (135, '09251', 'Dusky Skin', 'Dusky Skin', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (136, '09252', 'Dusky Skin Highlight', 'Dusky Skin', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (137, '09253', 'Flesh Wash', 'Washes I', 1, 20, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (138, '09254', 'Brown Wash', 'Washes I', 1, 20, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (139, '09255', 'Black Wash', 'Washes I Triad', 1, 20, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (140, '09256', 'Blond Shadow', 'Blond Hair', 1, 18, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (141, '09257', 'Blond Hair', 'Blond Hair', 1, 18, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (142, '09258', 'Blond Highlight', 'Blond Hair', 1, 18, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (143, '09259', 'Bronzed Shadow', 'Bronzed Skin Triad', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (144, '09260', 'Bronzed Skin', 'Bronzed Skin Triad', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (145, '09261', 'Bronzed Highlight', 'Bronzed Skin Triad', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (146, '09267', 'Sunset Purple', 'Evening Colors', 1, 6, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (147, '09268', 'Volcano Brown', 'Old Favorites II', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (148, '09271', 'Dirty Bone', 'Neutral Bone Colors', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (149, '09272', 'Graveyard Bone', 'Neutral Bone Colors', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (150, '09273', 'Splintered Bone', 'Neutral Bone Colors', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (151, '09274', 'Vampiric Shadow', 'Vampiric Skintones', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (152, '09275', 'Vampiric Skin', 'Vampiric Skintones', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (153, '09276', 'Vampiric Highlight', 'Vampiric Skintones', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (154, '09277', 'Spattered Crimson', 'Gory Reds Colors', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (155, '09278', 'Gory Red', 'Gory Reds Colors', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (156, '09279', 'Fresh Blood', 'Gory Reds Colors', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (157, '09280', 'Nightmare Black', 'Undead Colors', 1, 21, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (158, '09281', 'Brains Pink', 'Undead Colors', 1, 32, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (159, '09282', 'Maggot White', 'Undead Colors', 1, 11, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (160, '09283', 'Old West Rose', 'Old West Colors', 1, 32, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (161, '09284', 'Lonestar Leather', 'Old West Colors', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (162, '09285', 'Denim Blue', 'Old West Colors', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (163, '09286', 'Punk Rock Pink', 'Modern Brights Colors', 1, 32, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (164, '09287', 'Neon Yellow', 'Modern Brights Colors', 1, 13, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (165, '09288', 'LED Blue', 'Modern Brights Colors', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (166, '09289', 'Noir Black', 'IMEF Colors', 1, 21, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (167, '09290', 'Aircraft Grey', 'IMEF Colors', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (168, '09291', 'IMEF Olive', 'IMEF Colors', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (169, '09292', 'Bathalian Chitin', 'Alien Colors', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (170, '09293', 'Alien Flesh', 'Alien Colors', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (171, '09294', 'Alien Goo', 'Alien Colors', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (172, '09301', 'NMM Gold Shadow', '', 1, 13, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (173, '09302', 'NMM Gold Base', '', 1, 13, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (174, '09303', 'NMM Gold Highlight', '', 1, 13, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (175, '09304', 'Copper Verdigris', '', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (176, '09305', 'Tarnished Copper', '', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (177, '09306', 'New Copper', '', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (178, '09307', 'Red Liner', '', 1, 19, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (179, '09308', 'Green Liner', '', 1, 19, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (180, '09309', 'Sepia Liner', '', 1, 19, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (181, '09310', 'Sepia Wash', '', 1, 20, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (182, '09311', 'Stone Wash', '', 1, 20, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (183, '09312', 'Steel Wash', '', 1, 20, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (184, '09655', 'Bubblegum Pink', '', 1, 32, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (185, '09659', 'Ginger Cookie', '', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (186, '09673', 'Bright Silver', '', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (187, '09674', 'Sky Steel', '', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (188, '09675', 'Shadow Steel', '', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (189, '09676', 'Frontier Blue', '', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (190, '09678', 'Aquamarine Blue', '', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (191, '29801', 'Crimson Red', 'HD', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (192, '29802', 'Brilliant Red', 'HD', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (193, '29803', 'Entrail Pink', 'HD', 1, 32, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (194, '29804', 'Rusty Red', 'HD', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (195, '29805', 'Burning Orange', 'HD', 1, 35, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (196, '29806', 'Fireball Orange', 'HD', 1, 35, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (197, '29807', 'Mustard Yellow', 'HD', 1, 13, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (198, '29808', 'Golden Yellow', 'HD', 1, 13, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (199, '29809', 'Pale Saffron', 'HD', 1, 13, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (200, '29810', 'Mossy Green', 'HD', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (201, '29811', 'Turf Green', 'HD', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (202, '29812', 'Meadow Green', 'HD', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (203, '29813', 'Bright Turquoise', 'HD', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (204, '29814', 'Ice Blue', 'HD', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (205, '29815', 'Dragon Blue', 'HD', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (206, '29816', 'Solid Blue', 'HD', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (207, '29817', 'Winter Blue', 'HD', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (208, '29818', 'Nightsky Blue', 'HD', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (209, '29819', 'Twilight Purple', 'HD', 1, 6, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (210, '29820', 'Gem Purple', 'HD', 1, 6, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (211, '29821', 'Sunburn Flesh', 'HD', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (212, '29822', 'Suntan Flesh', 'HD', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (213, '29823', 'Caucasian Flesh', 'HD', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (214, '29824', 'Maiden Flesh', 'HD', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (215, '29825', 'Tusk Ivory', 'HD', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (216, '29826', 'Desert Tan', 'HD', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (217, '29827', 'Griffon Tan', 'HD', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (218, '29828', 'Woodland Brown', 'HD', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (219, '29829', 'Golden Brown', 'HD', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (220, '29830', 'Ruddy Brown', 'HD', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (221, '29831', 'Ashen Brown', 'HD', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (222, '29832', 'Concrete Grey', 'HD', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (223, '29833', 'Ash Grey', 'HD', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (224, '29834', 'Field Grey', 'HD', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (225, '29835', 'Dirty Grey', 'HD', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (226, '29836', 'Military Grey', 'HD', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (227, '29837', 'Armor Grey', 'HD', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (228, '29838', 'Stained Olive', 'HD', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (229, '29839', 'Maroon Red', 'HD', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (230, '29840', 'Garnet Red', 'HD', 1, 2, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (231, '29841', 'Witchcraft Purple', 'HD', 1, 6, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (232, '29842', 'Solid White', 'HD', 1, 14, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (233, '29843', 'Solid Black', 'HD', 1, 21, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (234, '29844', 'Blue Flame', 'HD', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (235, '29845', 'Gilded Yellow', 'HD', 1, 13, 2);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (236, '29846', 'Spruce Green', 'HD', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (237, '29847', 'Rich Indigo', 'HD', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (238, '29848', 'Jungle Camo', 'HD', 1, 4, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (239, '29849', 'Umber Brown', 'HD', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (240, '29850', 'EIf Flesh', 'HD', 1, 9, 3);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (241, '61113', 'Arthurian Blue', 'Heavy Gear', 1, 5, 1);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (242, '61121', 'R.A.M. Black', 'Heavy Gear', 1, 21, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (243, '61122', 'Durasheet Alloy', 'Heavy Gear', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (244, '61123', 'Skunkworks Gunmetal', 'Heavy Gear', 1, 10, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (245, '61125', 'Fallout Grey', 'Heavy Gear', 1, 8, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (246, '61130', 'Cat''s Eye Base', 'Heavy Gear', 1, 7, 4);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (247, 'WP1134', 'Soft Tone', null, 2, 34, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (248, 'WP1135', 'Strong Tone', null, 2, 34, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (249, 'WP1136', 'Dark Tone', null, 2, 34, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (250, 'WP1137', 'Green Tone', null, 2, 34, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (251, 'WP1138', 'Red Tone', null, 2, 34, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (252, 'WP1139', 'Blue Tone', null, 2, 34, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (253, 'WP1140', 'Purple Tone', null, 2, 34, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (254, 'WP1143', 'Flesh Wash', null, 2, 34, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (255, 'WP1105', 'Dragon Red', null, 2, 33, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (256, 'WP1107', 'Daemonic Yellow', null, 2, 33, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (257, 'WP1111', 'Greenskin', null, 2, 33, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (258, 'WP1114', 'Crystal Blue', null, 2, 33, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (259, 'WP1115', 'Ultramarine Blue', null, 2, 33, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (260, 'WP1118', 'Uniform Grey', null, 2, 33, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (261, 'WP1121', 'Desert Yellow', null, 2, 33, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (262, 'WP1123', 'Leather Brown', null, 2, 33, null);
INSERT INTO painting.Paints (id, Number, Color, Triad, brand_id, family_id, box_id) VALUES (263, 'WP1126', 'Barbarian Flesh', null, 2, 33, null);